# Created using application available at https://issue-forms-creator.netlify.app

name: 'Check list 2'
description: Review of script output to be used in report
title: 'Check list #1 [name of the DAP/organization]'
body:
  - type: markdown
    attributes:
      value: >-
        By filling in this form the [name of the DAP/organization]
        representative [full name of the DAP representative] declares that the
        final version of results, discussion and limitations of study report
        were carefully reviewed according to the items of the following
        check-list, also in the context of benchmarking with other participating
        datasources. 
  - type: checkboxes
    id: check_list_2
    attributes:
      label: Checklist
      options:
        - label: Presence of all expected tables and figures
          required: true
        - label: >-
            Number of subjects included in the study overall and exposure group
            (attrition)
          required: true
        - label: Age and sex, and calendar year distribution
          required: true
        - label: Expected follow-up if available
          required: true
        - label: >-
            If there are variables the have 0 counts or not available that
            should be available in data source
          required: true
        - label: Expected missing values
          required: true
        - label: Number and provenance of events if appropriate
          required: true
        - label: >-
            Distribution of covariates of the study population are in line with
            prior knowledge generated in the same database and with respect to
            other participating datasources
          required: true
        - label: Discussion and litimitation of study results
          required: true
